### ISSUE TITLE
TRACKER: Missing Info/Needs Filled

### ISSUE THREAD

**Issue by maddy0314** [ianchadd/va#30]
This issue is a catch-all for **issues of missing information** (incentive details, linked PDFs, images, etc.)

**Comment by maddy0314** [comment]
ISSUES WITH PAYOFF EMBED
- [ ] instructions_slider_va/VA_Quality_Guess_Entry: \va\details.pdf missing (BUTTON onclick page 404s)
- [ ] instructions_slider_va/VA_Quality_Guess_Entry: backup link not valid (LINK https://virtual-experimental-lab.github.io/ 404s)
- [ ] pt1_VA2/Debrief: \va\details.pdf missing (BUTTON onclick page 404s)
- [ ] pt1_VA2/Debrief: backup link not valid (LINK https://virtual-experimental-lab.github.io/ 404s)

**Comment by maddy0314** [comment]
QUESTIONNAIRES

- [ ] AI Questions (#27, #28)
- [ ] BSRI Short Form (#21)
